title: Stack Problems
description: My Personal Stack Problems
author: Objectprogr
github: https://github.com/objectprogr
about: I like all topics related to IT.
disqus_shortname: stackproblems
google_analytics: UA-98158396-5
avatar_url: /static/img/avatarNew.png

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "#"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-codepen
      link: "https://codepen.io/objectprogr/#"
    - icon: fa-github
      link: "https://github.com/objectprogr"

share:
  twitter_username: 
  fb_appid: 

urls:
    - text: How I learn
      url: /learn/
    - text: Challenge
      url: /challenge/
    - text: My Projects
      url: /projects/
    - text: English dictionary
      url: /english/
    - text: Category
      url: /category/30dayschallenge
    - text: About Me
      url: /about/
    - text: XML Feed
      url: /feed.xml

url: "https://objectprogr.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
